packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  eslint: ^9.19.0
  next: ^15.1.6
  prettier: ^3.4.2
  tailwindcss: ^4.0.3
  typescript: ^5.7.3
  tsx: ^4.19.2
  zod: ^3.24.1
  "@ai-sdk/openai": ^1.1.9
  ai: ^4.1.18

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0